### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-field-value-transform#1]
**Description**
In order to parse incoming data so that only certain records are passed through, this integration examines the records based on specified fields and compares them to a stated value through a designated operator.

**Requirements**
- [ ] Config parameters can handle multiple fields
- [ ] Config parameters can accept value that field should be tied to
- [ ] Config parameter takes in operator that if resolves to true passes on the record
- [ ] Available operators should include: 
  - [ ] >
  - [ ] >=
  - [ ] <
  - [ ] <=
  - [ ] TypeOf
  - [ ] Contains
  - [ ] Does Not Contain
  - [ ] StartsWith
  - [ ] EndsWith
  - [ ] [RegEx](https://www.npmjs.com/package/regex)
- [ ] Multiple requirements can be mixed in `and/or` relationships.

**Possible config**
In the following scenario, there are three parameters that are used to decide whether the record gets passed on. If either `param1 AND param2` OR `param1 AND param3` resolve to `true`, the record gets passed.

```
config : {
	"param1":{
		"field": "purchase_price",
		"operator": ">"
		"value": "200"
	},
	"param2": {
		"field": "item_name",
		"operator": "="
		"value": "Pants"
	},
	"param3": {
		"field": "item_name",
		"operator": "="
		"value": "Shirt"
	},
	"relationship":{
		"and": [
			"param1",
			"param2"
		],
		"or": {
			"and":[
					"param1",
					"param3"
				]
		}
	}
}
```

**Comment by benjamingregory** [comment]
```
config : {
	"filters":[{
		"field": "purchase_price",
		"operator": ">"
		"value": "200"
	},
	{
		"field": "item_name",
		"operator": "="
		"value": "Pants"
	},
	{
		"field": "item_name",
		"operator": "="
		"value": "Shirt"
	}],
       "relationship": "AND"
}
```

**Comment by benjamingregory** [comment]
config : {
	"filters":[{
		"field": "email_address",
		"operator": "contains"
		"value": "@astronomer.io"
	}],
       "relationship": "AND"
}

**Comment by byerc** [comment]
Beginning work on this.

**Comment by byerc** [comment]
Continuing this. Are we assuming that prior to running the workflow that we know exactly where the field is located in the json structure? This is an example of a survey response answer that we'd check for email...

`response.data[0].survey_data.170.answer`

Are we expected to input that into the config or actually just search every possible scenario? If so, it expands the scope of this activity significantly.

**Comment by benjamingregory** [comment]
I think that we would put the exact location of the field.

Potentially expand later but for now that should be sufficient.

**Comment by byerc** [comment]
Perfect. Thanks.

**Comment by byerc** [comment]
This will be focused on after postgres-sink issue is resolved.

**Comment by byerc** [comment]
Working on this to use flattened JSON data instead of raw responses.

**Comment by benjamingregory** [comment]
@byerc Leave a disclaimer in the readme making it clear that right now it requires flattened json as an input.

**Comment by byerc** [comment]
Fixing lint errors.
